/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbookmngt_tan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanmayee
 */
public final class AllPersonDatails extends javax.swing.JFrame {

    /**
     * Creates new form AllPersonDatails
     */
    DefaultTableModel model=new DefaultTableModel();
    Statement st;
    ResultSet rs;
    PreparedStatement ps=null;
    
    public AllPersonDatails() {
        initComponents();
        getDataTable();
    }
    
   public void getDataTable()
    {
        try {
            model.setColumnIdentifiers(new Object[]{"P_ID","FIRST NAME","LAST NAME","ADDRESS","CITY","STATE","ZIP","PHONE","ABOOK"});
            
            
            Connection conn=DBCon.getConnection();
            st=conn.createStatement();
            String searchQuery = "SELECT * FROM details_person";
            rs=st.executeQuery(searchQuery);
            Object[] row = new Object[9];
            int i=1;
            while(rs.next())
            {
                row[0] = rs.getString("p_id");
                row[1] = rs.getString("first_name");
                row[2] = rs.getString("last_name");
                row[3] = rs.getString("address_person");
                row[4] = rs.getString("city");
                row[5] = rs.getString("state");
                row[6] = rs.getInt("zip");
                row[7] = rs.getInt("ph_number");
                row[8] = rs.getInt("a_id");
                model.addRow(row);
            }
            personTable.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AllPersonDatails.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton_sortLname = new javax.swing.JButton();
        jButton_sortZip = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel7.setBackground(new java.awt.Color(255, 153, 0));
        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ALL PERSON DEATILS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EDIT");

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton_sortLname.setBackground(new java.awt.Color(102, 102, 102));
        jButton_sortLname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_sortLname.setForeground(new java.awt.Color(255, 255, 255));
        jButton_sortLname.setText("SORT BY LAST NAME ");
        jButton_sortLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_sortLnameMouseClicked(evt);
            }
        });

        jButton_sortZip.setBackground(new java.awt.Color(102, 102, 102));
        jButton_sortZip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_sortZip.setForeground(new java.awt.Color(255, 255, 255));
        jButton_sortZip.setText("SORT BY ZIP CODE");
        jButton_sortZip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_sortZipMouseClicked(evt);
            }
        });

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(personTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton_sortLname)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_sortZip)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sortLname)
                    .addComponent(jButton_sortZip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(778, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        HomePage hp=new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton_sortLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_sortLnameMouseClicked
        // TODO add your handling code here:
         try {
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"P_ID","FIRST NAME","LAST NAME","ADDRESS","CITY","STATE","ZIP","PHONE","ABOOK"});
                        
            Connection conn=DBCon.getConnection();
            st=conn.createStatement();
            String searchQuery = "SELECT * FROM details_person ORDER BY last_name";
            rs=st.executeQuery(searchQuery);
            Object[] row = new Object[9];
            int i=1;
            while(rs.next())
            {
                row[0] = rs.getString("p_id");
                row[1] = rs.getString("first_name");
                row[2] = rs.getString("last_name");
                row[3] = rs.getString("address_person");
                row[4] = rs.getString("city");
                row[5] = rs.getString("state");
                row[6] = rs.getInt("zip");
                row[7] = rs.getInt("ph_number");
                row[8] = rs.getInt("a_id");
                model.addRow(row);
            }
            personTable.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AllPersonDatails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_sortLnameMouseClicked

    private void jButton_sortZipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_sortZipMouseClicked
        // TODO add your handling code here:
        try {
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"P_ID","FIRST NAME","LAST NAME","ADDRESS","CITY","STATE","ZIP","PHONE","ABOOK"});
                        
            Connection conn=DBCon.getConnection();
            st=conn.createStatement();
            String searchQuery = "SELECT * FROM details_person ORDER BY zip";
            rs=st.executeQuery(searchQuery);
            Object[] row = new Object[9];
            int i=1;
            while(rs.next())
            {
                row[0] = rs.getString("p_id");
                row[1] = rs.getString("first_name");
                row[2] = rs.getString("last_name");
                row[3] = rs.getString("address_person");
                row[4] = rs.getString("city");
                row[5] = rs.getString("state");
                row[6] = rs.getInt("zip");
                row[7] = rs.getInt("ph_number");
                row[8] = rs.getInt("a_id");
                model.addRow(row);
            }
            personTable.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AllPersonDatails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_sortZipMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            int row=personTable.getSelectedRow();
            String eve;
            eve=(String) personTable.getModel().getValueAt(row, 0);
            
            Connection conn=DBCon.getConnection();
            ps=conn.prepareStatement("delete from details_person where p_id="+eve);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Deleted the person details !!");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AllAddressBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllPersonDatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllPersonDatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllPersonDatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllPersonDatails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllPersonDatails().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_sortLname;
    private javax.swing.JButton jButton_sortZip;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable personTable;
    // End of variables declaration//GEN-END:variables
}
