/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbookmngt_tan;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tanmayee
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanalHomePage = new javax.swing.JPanel();
        jButtonAddNewPerson = new javax.swing.JButton();
        jButtonAddNewAddressBook = new javax.swing.JButton();
        jButtonAllAddressBook = new javax.swing.JButton();
        jButtonAllRecords = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanalHomePage.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAddNewPerson.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAddNewPerson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddNewPerson.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddNewPerson.setText("ADD NEW PERSON");
        jButtonAddNewPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddNewPersonMouseClicked(evt);
            }
        });

        jButtonAddNewAddressBook.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAddNewAddressBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddNewAddressBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddNewAddressBook.setText("CREATE NEW ADDRESS BOOK");
        jButtonAddNewAddressBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddNewAddressBookMouseClicked(evt);
            }
        });

        jButtonAllAddressBook.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAllAddressBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAllAddressBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAllAddressBook.setText("SHOW ALL ADDRESS BOOK");
        jButtonAllAddressBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAllAddressBookMouseClicked(evt);
            }
        });

        jButtonAllRecords.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAllRecords.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAllRecords.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAllRecords.setText("ALL PERSON DEATILS");
        jButtonAllRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAllRecordsMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADDRESS BOOK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanalHomePageLayout = new javax.swing.GroupLayout(jPanalHomePage);
        jPanalHomePage.setLayout(jPanalHomePageLayout);
        jPanalHomePageLayout.setHorizontalGroup(
            jPanalHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanalHomePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanalHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanalHomePageLayout.createSequentialGroup()
                        .addComponent(jButtonAddNewAddressBook, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAllAddressBook, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanalHomePageLayout.createSequentialGroup()
                        .addComponent(jButtonAddNewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonAllRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanalHomePageLayout.setVerticalGroup(
            jPanalHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanalHomePageLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanalHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAllRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanalHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNewAddressBook, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAllAddressBook, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanalHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanalHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(780, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddNewPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddNewPersonMouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            AddNewPerson anp=new AddNewPerson();
            anp.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddNewPersonMouseClicked

    private void jButtonAllRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAllRecordsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        AllPersonDatails apd=new AllPersonDatails();
        apd.setVisible(true);
    }//GEN-LAST:event_jButtonAllRecordsMouseClicked

    private void jButtonAddNewAddressBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddNewAddressBookMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CreateNewAddressBook cnab=new CreateNewAddressBook();
        cnab.setVisible(true);
    }//GEN-LAST:event_jButtonAddNewAddressBookMouseClicked

    private void jButtonAllAddressBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAllAddressBookMouseClicked
        // TODO add your handling code here:
        this.dispose();
        AllAddressBook adb=new AllAddressBook();
        adb.setVisible(true);
    }//GEN-LAST:event_jButtonAllAddressBookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewAddressBook;
    private javax.swing.JButton jButtonAddNewPerson;
    private javax.swing.JButton jButtonAllAddressBook;
    private javax.swing.JButton jButtonAllRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanalHomePage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
